"""D-118 client benchmark: synthetic scenarios (public, invented data; no private memory).

Each scenario shows the client LLM a ``memory.query`` result (the old multi-statement memory among
distractors) and then a new fact from the user. 30 UPDATE scenarios change exactly one statement of
one shown memory (gold: that memory's clue, the outdated statement and the key phrase the quote must
contain); 10 CONTROLS add a related fact that updates nothing (gold: no ``updates``).
"""

from __future__ import annotations

from dataclasses import dataclass

#: (topic key, title, statements); every memory is ONE fact item with four statements
MEMORIES: dict[str, tuple[str, list[str]]] = {
    "cache": (
        "Cache settings",
        [
            "The API cache TTL is 60 seconds for every endpoint.",
            "The cache backend is Redis 7 on the api host.",
            "Cache keys are prefixed with the service name.",
            "The cache is flushed on every deploy.",
        ],
    ),
    "deploy": (
        "Deploy process",
        [
            "Deploys run from the main branch via GitHub Actions.",
            "Production deploys happen on Tuesdays and Thursdays.",
            "The deploy script is deploy/scripts/deploy.sh.",
            "Rollbacks use the previous image tag.",
        ],
    ),
    "db": (
        "Database setup",
        [
            "The primary database is Postgres 16 on db-1.",
            "Backups run nightly at 02:00 UTC.",
            "The connection pool size is 20.",
            "Read replicas are not used.",
        ],
    ),
    "tests": (
        "Test conventions",
        [
            "Unit tests live in tests/unit and run with pytest.",
            "Integration tests need HLM_TEST_DSN.",
            "The CI timeout is 15 minutes.",
            "Coverage must stay above 80 percent.",
        ],
    ),
    "auth": (
        "Auth service",
        [
            "Access tokens expire after 24 hours.",
            "Refresh tokens are valid for 30 days.",
            "The auth service runs on port 8081.",
            "Passwords are hashed with bcrypt.",
        ],
    ),
    "logging": (
        "Logging",
        [
            "Logs are shipped to Loki via promtail.",
            "The default log level is INFO.",
            "Request logs are kept for 14 days.",
            "Error alerts go to the #ops-alerts Slack channel.",
        ],
    ),
    "frontend": (
        "Frontend build",
        [
            "The frontend is built with Vite 5.",
            "Node 20 is required for the build.",
            "The build output goes to web/dist.",
            "Storybook runs on port 6006.",
        ],
    ),
    "queue": (
        "Queue worker",
        [
            "Background jobs use RabbitMQ 3.12.",
            "The worker concurrency is 4.",
            "Failed jobs are retried 3 times.",
            "The dead-letter queue is jobs.dlq.",
        ],
    ),
    "payments": (
        "Payments",
        [
            "Payments are processed through Stripe.",
            "Stripe webhooks are received at /api/stripe/webhook.",
            "The payment currency is EUR.",
            "Refunds require manager approval.",
        ],
    ),
    "monitoring": (
        "Monitoring",
        [
            "Prometheus scrapes metrics every 30 seconds.",
            "Grafana dashboards live in ops/grafana.",
            "The uptime SLO is 99.5 percent.",
            "PagerDuty handles on-call paging.",
        ],
    ),
    "release": (
        "Release versioning",
        [
            "Releases follow semantic versioning.",
            "The current release line is 2.4.",
            "Release notes are written in CHANGELOG.md.",
            "Release tags are signed with the release GPG key.",
        ],
    ),
    "storage": (
        "Upload storage",
        [
            "User uploads are stored in the S3 bucket acme-uploads.",
            "Uploads larger than 50 MB are rejected.",
            "Files are encrypted with SSE-S3.",
            "Thumbnails are generated by the media worker.",
        ],
    ),
}
TOPICS = list(MEMORIES)


def body(topic: str) -> str:
    return " ".join(MEMORIES[topic][1])


def clue_vid(topic: str) -> int:
    return 400 + 17 * TOPICS.index(topic)


@dataclass(frozen=True, slots=True)
class Scenario:
    sid: str
    topic: str  # the memory the user asks about (always shown)
    fact: str  # what the user says
    statement: int | None  # index of the outdated statement (None = control)
    key: str | None  # the phrase a correct old_span must contain

    @property
    def is_update(self) -> bool:
        return self.statement is not None

    @property
    def gold_statement(self) -> str | None:
        return None if self.statement is None else MEMORIES[self.topic][1][self.statement]


UPDATES: list[Scenario] = [
    Scenario("u01", "cache", "We raised the API cache TTL to 300 seconds for every endpoint.", 0, "60 seconds"),
    Scenario("u02", "cache", "The cache backend moved to Valkey 8 on the api host.", 1, "Redis 7"),
    Scenario("u03", "deploy", "Production deploys now happen every weekday.", 1, "Tuesdays and Thursdays"),
    Scenario("u04", "deploy", "Deploys from main now run via Buildkite, not GitHub Actions.", 0, "GitHub Actions"),
    Scenario("u05", "deploy", "The deploy script moved to ops/deploy.sh.", 2, "deploy/scripts/deploy.sh"),
    Scenario("u06", "db", "We upgraded the primary database to Postgres 17 on db-1.", 0, "Postgres 16"),
    Scenario("u07", "db", "Nightly backups now run at 04:00 UTC.", 1, "02:00 UTC"),
    Scenario("u08", "db", "The connection pool size was raised to 50.", 2, "20"),
    Scenario("u09", "tests", "The CI timeout is now 30 minutes.", 2, "15 minutes"),
    Scenario("u10", "tests", "Coverage must now stay above 85 percent.", 3, "80 percent"),
    Scenario("u11", "auth", "Access tokens now expire after 8 hours.", 0, "24 hours"),
    Scenario("u12", "auth", "The auth service moved to port 9000.", 2, "8081"),
    Scenario("u13", "auth", "We switched password hashing from bcrypt to argon2id.", 3, "bcrypt"),
    Scenario("u14", "logging", "The default log level is WARN now.", 1, "INFO"),
    Scenario("u15", "logging", "Request logs are now kept for 30 days.", 2, "14 days"),
    Scenario("u16", "logging", "Error alerts now go to the #incidents Slack channel.", 3, "#ops-alerts"),
    Scenario("u17", "frontend", "We upgraded the frontend build to Vite 6.", 0, "Vite 5"),
    Scenario("u18", "frontend", "The build now requires Node 22.", 1, "Node 20"),
    Scenario("u19", "queue", "The worker concurrency was raised to 8.", 1, "4"),
    Scenario("u20", "queue", "Failed jobs are now retried 5 times.", 2, "3 times"),
    Scenario("u21", "queue", "The dead-letter queue was renamed to jobs.dead.", 3, "jobs.dlq"),
    Scenario("u22", "payments", "The payment currency changed to USD.", 2, "EUR"),
    Scenario("u23", "payments", "Stripe webhooks now arrive at /webhooks/stripe.", 1, "/api/stripe/webhook"),
    Scenario("u24", "monitoring", "Prometheus now scrapes metrics every 15 seconds.", 0, "30 seconds"),
    Scenario("u25", "monitoring", "The uptime SLO was raised to 99.9 percent.", 2, "99.5 percent"),
    Scenario("u26", "monitoring", "On-call paging moved from PagerDuty to Opsgenie.", 3, "PagerDuty"),
    Scenario("u27", "release", "The current release line is 3.0 now.", 1, "2.4"),
    Scenario("u28", "storage", "Uploads up to 100 MB are accepted now.", 1, "50 MB"),
    Scenario("u29", "storage", "User uploads moved to the S3 bucket acme-user-files.", 0, "acme-uploads"),
    Scenario("u30", "storage", "Files are now encrypted with SSE-KMS.", 2, "SSE-S3"),
]
CONTROLS: list[Scenario] = [
    Scenario("c01", "cache", "The cache hit rate is shown on the Grafana dashboard 'API cache'.", None, None),
    Scenario("c02", "deploy", "Deploy announcements are posted in the #releases Slack channel.", None, None),
    Scenario("c03", "db", "db-1 has 64 GB of RAM.", None, None),
    Scenario("c04", "tests", "Integration tests can run in parallel with pytest -n 4.", None, None),
    Scenario("c05", "auth", "The auth service exposes a /healthz endpoint.", None, None),
    Scenario("c06", "logging", "Loki queries should filter by the service label first.", None, None),
    Scenario("c07", "frontend", "The frontend uses TanStack Query for data fetching.", None, None),
    Scenario("c08", "storage", "The media worker also strips EXIF data from uploaded images.", None, None),
    Scenario("c09", "payments", "Stripe test mode is used on staging.", None, None),
    Scenario("c10", "release", "Release branches are named release/<major>.<minor>.", None, None),
]
SCENARIOS = UPDATES + CONTROLS


def shown_topics(s: Scenario) -> list[str]:
    """The query's hits: the scenario's memory plus two deterministic distractors; the memory is
    first or second (alternating) so position is no cue."""
    i = TOPICS.index(s.topic)
    others = [TOPICS[(i + 3) % len(TOPICS)], TOPICS[(i + 7) % len(TOPICS)]]
    n = int(s.sid[1:])
    return [others[0], s.topic, others[1]] if n % 2 else [s.topic, *others]


def query_result(s: Scenario) -> dict:
    """A ``memory.query`` result in the server's shape (card, hits with chunk clues, budget)."""
    hits = []
    for rank, topic in enumerate(shown_topics(s)):
        title, _st = MEMORIES[topic]
        hits.append(
            {
                "clue": f"v{clue_vid(topic)}.0",
                "kind": "fact",
                "title": title,
                "preview": body(topic),
                "score": round(0.0331 - 0.0017 * rank, 4),
                "valid_from": "2026-08-14T09:12:00.000000Z",
                "tags": [],
                "device_scope": "all",
            }
        )
    return {
        "contract_version": "query/2",
        "project": "acme-api",
        "card": {"clue": "v12", "text": "acme-api: the ACME customer API (Python, Postgres)."},
        "hits": hits,
        "evidence": "matched",
        "budget": {"limit": 2000, "used": 431, "tokenizer": "o200k_base"},
    }


__all__ = ["CONTROLS", "MEMORIES", "SCENARIOS", "UPDATES", "Scenario", "body", "clue_vid", "query_result"]
